import type { Metadata } from "next";
import "./globals.css";
import Navbar from "@/components/navbar/index.tsx";

import { Red_Hat_Display } from "next/font/google";

const Comforta = Red_Hat_Display({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${Comforta.className} antialiased`}
      >
        <Navbar />
        {children}
      </body>
    </html>
  );
}
